sudo: required
cache:
  - apt

# Build all valid Ubuntu/ROS combinations available on Travis VMs.
language: cpp

matrix:
  include:
  - name: "Xenial kinetic"
    dist: xenial
    env: ROS_DISTRO=kinetic

# Configuration variables. All variables are global now, but this can be used to
# trigger a build matrix for different ROS distributions if desired.
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
################################################################################

env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - toolset_branch: master
    - server_type: travis
    - ros_release_name: kinetic
    - ubuntu_version_name: xenial
    - used_modules: check_cache,check_build
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

# Install system dependencies, namely a very barebones ROS setup.
before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update -qq
  - sudo apt-get install dpkg
  - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool python-catkin-tools ros-$ROS_DISTRO-desktop-full
  - source /opt/ros/$ROS_DISTRO/setup.bash
  # Prepare rosdep to install dependencies.
  - sudo rosdep init
  - rosdep update

# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin build
  - source devel/setup.bash
  - cd ~/catkin_ws/src

# Install all dependencies, using wstool first and rosdep second.
# wstool looks for a ROSINSTALL_FILE defined in the environment variables.
before_script:
  # Install Other dependencies
  - sudo add-apt-repository -y ppa:dartsim/ppa
  - sudo add-apt-repository -y ppa:personalrobotics/ppa
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
  - sudo apt-get install cmake build-essential libboost-filesystem-dev libdart6-optimizer-nlopt-dev libdart6-utils-dev libdart6-utils-urdf-dev libmicrohttpd-dev libompl-dev libtinyxml2-dev libyaml-cpp-dev
  - sudo apt-get purge -y ros-kinetic-dartsim
  - sudo pip install pybind11
  # source dependencies: install using wstool.
  - cd ~/catkin_ws/src
  - wstool init
  - if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
  - wstool up
  
script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin build
  - source devel/setup.bash
  
notifications:
  slack:
    rooms:
      - secure: IKeTZ/bkFkp+CR8+7YlxXezpp8rsi2rI47gzxU1YjVcFH+q8EfP6HQM6ZvxurvV/Ka4zeLvOPY54oj7bw64OX1XbyACgDrQY1fWWtQLj0EpBRWY7DtcEdo6WB0LYrebiVVG/vTIyyG+L4tm54rn9Cfn9958bgGZYbdrPU0IyIhKKjpZbYxEWA8ng7gpvAcr26d+2Gzg/Fxv7a89lYXp9gBgS8inJc4TqASTuKib7r0SRSrI+VmegVTwa/nCKQhNMyPvsb/wU0AUeTuajoCGdRTQSz5VYP3mXarDuMvcSBNn4GE/4yMuS1/3nhs85rWfvN9bFSG+o+cPYW+VfxhP+LVFFIReUfm3I+Ekwii9KOvryTtRF20NRCAiQUDmidPlgXO999eurzaA5mtiELd84DPBV48lBIY9DZaLZOGF8g5Bgi2lzfRFRrX8qjhKRmzBpr6XIKmoQxTSL4qPNR6kxZhyxZA6YoNfPGtP7KilfBYe1YqDuIpwZ1bjyEw2ypfLirOawZb5khdBS6tx76nAqbh9ytKAdPgLYFBkmf2YPfZY1DanfcRIvgxKV6ZO46tFXzB8mPUuMWbCXnJ38zF4wuGf/BF3FeaX8GQ78VUJfuFadkMKXSKbij6gkJ3RK9N2PmihQxwvZTpxFUN8ctoyUfiaczmZWtwkET38hcAmfGcs=
